/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felip
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_Main = new javax.swing.JPanel();
        TP_Main = new javax.swing.JTabbedPane();
        M_Create = new javax.swing.JPanel();
        TXT_Universe = new javax.swing.JLabel();
        P_bar = new javax.swing.JPanel();
        TXT_Life = new javax.swing.JLabel();
        BTN_Cuni = new javax.swing.JButton();
        BTN_Clife = new javax.swing.JButton();
        TXT_NameP = new javax.swing.JLabel();
        TF_NameP = new javax.swing.JTextField();
        TXT_ID = new javax.swing.JLabel();
        TF_ID = new javax.swing.JTextField();
        TXT_Pwr = new javax.swing.JLabel();
        CB_Pwr = new javax.swing.JComboBox<>();
        TXT_Age = new javax.swing.JLabel();
        SP_Age = new javax.swing.JSpinner();
        TXT_NameU = new javax.swing.JLabel();
        TF_NameU = new javax.swing.JTextField();
        TXT_Univp = new javax.swing.JLabel();
        TXT_Race = new javax.swing.JLabel();
        CB_Race = new javax.swing.JComboBox<>();
        CB_Univp = new javax.swing.JComboBox<>();
        M_BusqElim = new javax.swing.JPanel();
        M_Mod = new javax.swing.JPanel();
        TXT_Universe1 = new javax.swing.JLabel();
        P_bar1 = new javax.swing.JPanel();
        TXT_Life1 = new javax.swing.JLabel();
        BTN_Cuni1 = new javax.swing.JButton();
        BTN_Clife1 = new javax.swing.JButton();
        TXT_NameP1 = new javax.swing.JLabel();
        TF_NameP1 = new javax.swing.JTextField();
        TXT_ID1 = new javax.swing.JLabel();
        TF_ID1 = new javax.swing.JTextField();
        TXT_Pwr1 = new javax.swing.JLabel();
        CB_Pwr1 = new javax.swing.JComboBox<>();
        TXT_Age1 = new javax.swing.JLabel();
        SP_Age1 = new javax.swing.JSpinner();
        TXT_NameU1 = new javax.swing.JLabel();
        TF_NameU1 = new javax.swing.JTextField();
        TXT_Univp1 = new javax.swing.JLabel();
        TXT_Race1 = new javax.swing.JLabel();
        CB_Race1 = new javax.swing.JComboBox<>();
        CB_Univp1 = new javax.swing.JComboBox<>();
        PB_SeresCargados = new javax.swing.JProgressBar();
        BTN_Personas = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Control de Amantos");
        setResizable(false);

        TXT_Universe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TXT_Universe.setText("UNIVERSOS");

        P_bar.setBackground(new java.awt.Color(0, 0, 0));
        P_bar.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout P_barLayout = new javax.swing.GroupLayout(P_bar);
        P_bar.setLayout(P_barLayout);
        P_barLayout.setHorizontalGroup(
            P_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        P_barLayout.setVerticalGroup(
            P_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        TXT_Life.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TXT_Life.setText("SERES VIVOS");

        BTN_Cuni.setText("Crear Universo");
        BTN_Cuni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BTN_Clife.setText("Crear Ser Vivo");
        BTN_Clife.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_Clife.setEnabled(false);
        BTN_Clife.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_ClifeMouseClicked(evt);
            }
        });

        TXT_NameP.setText("Nombre:");

        TF_NameP.setEnabled(false);
        TF_NameP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_NamePActionPerformed(evt);
            }
        });

        TXT_ID.setText("ID:");

        TF_ID.setEnabled(false);
        TF_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_IDActionPerformed(evt);
            }
        });

        TXT_Pwr.setText("Poder:");

        CB_Pwr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        CB_Pwr.setEnabled(false);

        TXT_Age.setText("Edad:");

        SP_Age.setEnabled(false);

        TXT_NameU.setText("Nombre:");

        TF_NameU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_NameUActionPerformed(evt);
            }
        });

        TXT_Univp.setText("Universo de procedencia: ");

        TXT_Race.setText("Raza:");

        CB_Race.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Amanto" }));
        CB_Race.setEnabled(false);

        CB_Univp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_Univp.setEnabled(false);

        javax.swing.GroupLayout M_CreateLayout = new javax.swing.GroupLayout(M_Create);
        M_Create.setLayout(M_CreateLayout);
        M_CreateLayout.setHorizontalGroup(
            M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, M_CreateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_Clife, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(M_CreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(M_CreateLayout.createSequentialGroup()
                        .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_Universe, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(M_CreateLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(TXT_NameU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_NameU, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_Cuni, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(M_CreateLayout.createSequentialGroup()
                        .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_Life, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(M_CreateLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(M_CreateLayout.createSequentialGroup()
                                        .addComponent(TXT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TXT_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(M_CreateLayout.createSequentialGroup()
                                        .addComponent(TXT_NameP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TF_NameP, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(TXT_Pwr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CB_Pwr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SP_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(M_CreateLayout.createSequentialGroup()
                                        .addComponent(TXT_Race, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CB_Race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(M_CreateLayout.createSequentialGroup()
                                        .addComponent(TXT_Univp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CB_Univp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(149, Short.MAX_VALUE))))
        );
        M_CreateLayout.setVerticalGroup(
            M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_CreateLayout.createSequentialGroup()
                .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(M_CreateLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TXT_Universe, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_NameU)
                            .addComponent(TF_NameU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(M_CreateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_Cuni, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(P_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXT_Life, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_NameP)
                    .addComponent(TF_NameP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_Pwr)
                    .addComponent(CB_Pwr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_Univp)
                    .addComponent(CB_Univp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, M_CreateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(M_CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_ID)
                            .addComponent(TF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_Age)
                            .addComponent(SP_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_Race)
                            .addComponent(CB_Race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(M_CreateLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(BTN_Clife, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        TP_Main.addTab("Creacion", M_Create);

        javax.swing.GroupLayout M_BusqElimLayout = new javax.swing.GroupLayout(M_BusqElim);
        M_BusqElim.setLayout(M_BusqElimLayout);
        M_BusqElimLayout.setHorizontalGroup(
            M_BusqElimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        M_BusqElimLayout.setVerticalGroup(
            M_BusqElimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        TP_Main.addTab("Busqueda / Eliminacion", M_BusqElim);

        TXT_Universe1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TXT_Universe1.setText("UNIVERSOS");

        P_bar1.setBackground(new java.awt.Color(0, 0, 0));
        P_bar1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout P_bar1Layout = new javax.swing.GroupLayout(P_bar1);
        P_bar1.setLayout(P_bar1Layout);
        P_bar1Layout.setHorizontalGroup(
            P_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        P_bar1Layout.setVerticalGroup(
            P_bar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        TXT_Life1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TXT_Life1.setText("SERES VIVOS");

        BTN_Cuni1.setText("Modificar Universo");
        BTN_Cuni1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_Cuni1.setEnabled(false);

        BTN_Clife1.setText("Modificar Ser Vivo");
        BTN_Clife1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_Clife1.setEnabled(false);
        BTN_Clife1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_Clife1MouseClicked(evt);
            }
        });

        TXT_NameP1.setText("Nombre:");

        TF_NameP1.setEnabled(false);
        TF_NameP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_NameP1ActionPerformed(evt);
            }
        });

        TXT_ID1.setText("ID:");

        TF_ID1.setEnabled(false);
        TF_ID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_ID1ActionPerformed(evt);
            }
        });

        TXT_Pwr1.setText("Poder:");

        CB_Pwr1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        CB_Pwr1.setEnabled(false);

        TXT_Age1.setText("Edad:");

        SP_Age1.setEnabled(false);

        TXT_NameU1.setText("Nombre:");

        TF_NameU1.setEnabled(false);
        TF_NameU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_NameU1ActionPerformed(evt);
            }
        });

        TXT_Univp1.setText("Universo de procedencia: ");

        TXT_Race1.setText("Raza:");

        CB_Race1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Amanto" }));
        CB_Race1.setEnabled(false);

        CB_Univp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_Univp1.setEnabled(false);

        javax.swing.GroupLayout M_ModLayout = new javax.swing.GroupLayout(M_Mod);
        M_Mod.setLayout(M_ModLayout);
        M_ModLayout.setHorizontalGroup(
            M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_bar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(M_ModLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(M_ModLayout.createSequentialGroup()
                        .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_Universe1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(M_ModLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(TXT_NameU1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_NameU1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_Cuni1)
                        .addGap(28, 28, 28))
                    .addGroup(M_ModLayout.createSequentialGroup()
                        .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_Life1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(M_ModLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(M_ModLayout.createSequentialGroup()
                                        .addComponent(TXT_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TF_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TXT_Age1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(M_ModLayout.createSequentialGroup()
                                        .addComponent(TXT_NameP1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TF_NameP1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(TXT_Pwr1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CB_Pwr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SP_Age1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(M_ModLayout.createSequentialGroup()
                                        .addComponent(TXT_Race1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CB_Race1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(M_ModLayout.createSequentialGroup()
                                        .addComponent(TXT_Univp1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CB_Univp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(149, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, M_ModLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_Clife1)
                .addGap(28, 28, 28))
        );
        M_ModLayout.setVerticalGroup(
            M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_ModLayout.createSequentialGroup()
                .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(M_ModLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TXT_Universe1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_NameU1)
                            .addComponent(TF_NameU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(M_ModLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_Cuni1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(P_bar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXT_Life1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_NameP1)
                    .addComponent(TF_NameP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_Pwr1)
                    .addComponent(CB_Pwr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_Univp1)
                    .addComponent(CB_Univp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, M_ModLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(M_ModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_ID1)
                            .addComponent(TF_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_Age1)
                            .addComponent(SP_Age1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_Race1)
                            .addComponent(CB_Race1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(M_ModLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(BTN_Clife1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        TP_Main.addTab("Modificacion", M_Mod);

        javax.swing.GroupLayout P_MainLayout = new javax.swing.GroupLayout(P_Main);
        P_Main.setLayout(P_MainLayout);
        P_MainLayout.setHorizontalGroup(
            P_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TP_Main)
        );
        P_MainLayout.setVerticalGroup(
            P_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TP_Main)
        );

        BTN_Personas.setText("Cargar Personas");
        BTN_Personas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(PB_SeresCargados, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_Personas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PB_SeresCargados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Personas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(P_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_NamePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_NamePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_NamePActionPerformed

    private void TF_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_IDActionPerformed

    private void TF_NameUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_NameUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_NameUActionPerformed

    private void BTN_ClifeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_ClifeMouseClicked
        // TODO add your handling code here:
        
        System.out.println("ouch");
    }//GEN-LAST:event_BTN_ClifeMouseClicked

    private void BTN_Clife1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_Clife1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_Clife1MouseClicked

    private void TF_NameP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_NameP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_NameP1ActionPerformed

    private void TF_ID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_ID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_ID1ActionPerformed

    private void TF_NameU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_NameU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_NameU1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Clife;
    private javax.swing.JButton BTN_Clife1;
    private javax.swing.JButton BTN_Cuni;
    private javax.swing.JButton BTN_Cuni1;
    private javax.swing.JToggleButton BTN_Personas;
    private javax.swing.JComboBox<String> CB_Pwr;
    private javax.swing.JComboBox<String> CB_Pwr1;
    private javax.swing.JComboBox<String> CB_Race;
    private javax.swing.JComboBox<String> CB_Race1;
    private javax.swing.JComboBox<String> CB_Univp;
    private javax.swing.JComboBox<String> CB_Univp1;
    private javax.swing.JPanel M_BusqElim;
    private javax.swing.JPanel M_Create;
    private javax.swing.JPanel M_Mod;
    private javax.swing.JProgressBar PB_SeresCargados;
    private javax.swing.JPanel P_Main;
    private javax.swing.JPanel P_bar;
    private javax.swing.JPanel P_bar1;
    private javax.swing.JSpinner SP_Age;
    private javax.swing.JSpinner SP_Age1;
    private javax.swing.JTextField TF_ID;
    private javax.swing.JTextField TF_ID1;
    private javax.swing.JTextField TF_NameP;
    private javax.swing.JTextField TF_NameP1;
    private javax.swing.JTextField TF_NameU;
    private javax.swing.JTextField TF_NameU1;
    private javax.swing.JTabbedPane TP_Main;
    private javax.swing.JLabel TXT_Age;
    private javax.swing.JLabel TXT_Age1;
    private javax.swing.JLabel TXT_ID;
    private javax.swing.JLabel TXT_ID1;
    private javax.swing.JLabel TXT_Life;
    private javax.swing.JLabel TXT_Life1;
    private javax.swing.JLabel TXT_NameP;
    private javax.swing.JLabel TXT_NameP1;
    private javax.swing.JLabel TXT_NameU;
    private javax.swing.JLabel TXT_NameU1;
    private javax.swing.JLabel TXT_Pwr;
    private javax.swing.JLabel TXT_Pwr1;
    private javax.swing.JLabel TXT_Race;
    private javax.swing.JLabel TXT_Race1;
    private javax.swing.JLabel TXT_Universe;
    private javax.swing.JLabel TXT_Universe1;
    private javax.swing.JLabel TXT_Univp;
    private javax.swing.JLabel TXT_Univp1;
    // End of variables declaration//GEN-END:variables
}
